env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  env:
    matrix:
      - TARGET: amd64
        TARGET_ARCH: amd64
      - TARGET: arm64
        TARGET_ARCH: aarch64
      - TARGET: i386
        TARGET_ARCH: i386
  freebsd_instance:
    matrix:
      image: freebsd-13-0-current-amd64-v20190117
      image: freebsd-12-0-release-amd64
    cpu: 8
    memory: 24G
  script:
    - sh -ex tools/tools/cirrus-ci/cirrus.sh
